fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Adipose_Subcutaneous -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.899 -a1 5.574 -prefix fastENLOC_output/CAD_Adipose_Subcutaneous
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Adipose_Visceral_Omentum -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.769 -a1 5.414 -prefix fastENLOC_output/CAD_Adipose_Visceral_Omentum
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Adrenal_Gland -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.670 -a1 5.449 -prefix fastENLOC_output/CAD_Adrenal_Gland
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Artery_Aorta -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -11.125 -a1 6.204 -prefix fastENLOC_output/CAD_Artery_Aorta
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Artery_Coronary -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.683 -a1 5.651 -prefix fastENLOC_output/CAD_Artery_Coronary
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Artery_Tibial -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -11.005 -a1 5.816 -prefix fastENLOC_output/CAD_Artery_Tibial
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Amygdala -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.470 -a1 4.841 -prefix fastENLOC_output/CAD_Brain_Amygdala
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Anterior_cingulate_cortex_BA24 -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.489 -a1 4.818 -prefix fastENLOC_output/CAD_Brain_Anterior_cingulate_cortex_BA24
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Caudate_basal_ganglia -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.592 -a1 5.095 -prefix fastENLOC_output/CAD_Brain_Caudate_basal_ganglia
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Cerebellar_Hemisphere -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.651 -a1 5.193 -prefix fastENLOC_output/CAD_Brain_Cerebellar_Hemisphere
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Cerebellum -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.658 -a1 5.123 -prefix fastENLOC_output/CAD_Brain_Cerebellum
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Cortex -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.601 -a1 5.073 -prefix fastENLOC_output/CAD_Brain_Cortex
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Frontal_Cortex_BA9 -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.565 -a1 5.012 -prefix fastENLOC_output/CAD_Brain_Frontal_Cortex_BA9
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Hippocampus -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.521 -a1 4.949 -prefix fastENLOC_output/CAD_Brain_Hippocampus
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Hypothalamus -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.522 -a1 4.953 -prefix fastENLOC_output/CAD_Brain_Hypothalamus
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Nucleus_accumbens_basal_ganglia -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.568 -a1 5.000 -prefix fastENLOC_output/CAD_Brain_Nucleus_accumbens_basal_ganglia
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Putamen_basal_ganglia -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.642 -a1 5.419 -prefix fastENLOC_output/CAD_Brain_Putamen_basal_ganglia
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Spinal_cord_cervical_c-1 -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.541 -a1 5.258 -prefix fastENLOC_output/CAD_Brain_Spinal_cord_cervical_c-1
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Substantia_nigra -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.483 -a1 4.996 -prefix fastENLOC_output/CAD_Brain_Substantia_nigra
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Breast_Mammary_Tissue -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.746 -a1 5.424 -prefix fastENLOC_output/CAD_Breast_Mammary_Tissue
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Cells_Cultured_fibroblasts -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.804 -a1 5.332 -prefix fastENLOC_output/CAD_Cells_Cultured_fibroblasts
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Cells_EBV-transformed_lymphocytes -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.495 -a1 4.909 -prefix fastENLOC_output/CAD_Cells_EBV-transformed_lymphocytes
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Colon_Sigmoid -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.648 -a1 5.160 -prefix fastENLOC_output/CAD_Colon_Sigmoid
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Colon_Transverse -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.683 -a1 5.176 -prefix fastENLOC_output/CAD_Colon_Transverse
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Esophagus_Gastroesophageal_Junction -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.732 -a1 5.436 -prefix fastENLOC_output/CAD_Esophagus_Gastroesophageal_Junction
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Esophagus_Mucosa -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.651 -a1 4.873 -prefix fastENLOC_output/CAD_Esophagus_Mucosa
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Esophagus_Muscularis -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.788 -a1 5.350 -prefix fastENLOC_output/CAD_Esophagus_Muscularis
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Heart_Atrial_Appendage -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.743 -a1 5.425 -prefix fastENLOC_output/CAD_Heart_Atrial_Appendage
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Heart_Left_Ventricle -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.700 -a1 5.411 -prefix fastENLOC_output/CAD_Heart_Left_Ventricle
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Kidney_Cortex -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.457 -a1 4.856 -prefix fastENLOC_output/CAD_Kidney_Cortex
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Liver -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.610 -a1 5.466 -prefix fastENLOC_output/CAD_Liver
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Lung -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.768 -a1 5.297 -prefix fastENLOC_output/CAD_Lung
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Minor_Salivary_Gland -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.450 -a1 4.453 -prefix fastENLOC_output/CAD_Minor_Salivary_Gland
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Muscle_Skeletal -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.774 -a1 5.419 -prefix fastENLOC_output/CAD_Muscle_Skeletal
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Nerve_Tibial -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.874 -a1 5.338 -prefix fastENLOC_output/CAD_Nerve_Tibial
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Ovary -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.482 -a1 4.581 -prefix fastENLOC_output/CAD_Ovary
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Pancreas -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.658 -a1 5.224 -prefix fastENLOC_output/CAD_Pancreas
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Pituitary -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.580 -a1 4.942 -prefix fastENLOC_output/CAD_Pituitary
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Prostate -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.583 -a1 5.128 -prefix fastENLOC_output/CAD_Prostate
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Skin_Not_Sun_Exposed -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.746 -a1 5.165 -prefix fastENLOC_output/CAD_Skin_Not_Sun_Exposed
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Skin_Sun_Exposed -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.712 -a1 4.958 -prefix fastENLOC_output/CAD_Skin_Sun_Exposed
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Small_Intestine_Terminal_Ileum -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.596 -a1 5.253 -prefix fastENLOC_output/CAD_Small_Intestine_Terminal_Ileum
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Spleen -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.785 -a1 5.612 -prefix fastENLOC_output/CAD_Spleen
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Stomach -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.618 -a1 5.162 -prefix fastENLOC_output/CAD_Stomach
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Testis -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.648 -a1 4.594 -prefix fastENLOC_output/CAD_Testis
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Thyroid -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.824 -a1 5.187 -prefix fastENLOC_output/CAD_Thyroid
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Uterus -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.516 -a1 5.206 -prefix fastENLOC_output/CAD_Uterus
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Vagina -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.479 -a1 4.975 -prefix fastENLOC_output/CAD_Vagina
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Whole_Blood -g gwas_data/gwas/torus/CAD.torus.pip.gz -a0 -10.782 -a1 5.416 -prefix fastENLOC_output/CAD_Whole_Blood
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Adipose_Subcutaneous -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.472 -a1 3.410 -prefix fastENLOC_output/HDL_Adipose_Subcutaneous
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Adipose_Visceral_Omentum -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.425 -a1 2.663 -prefix fastENLOC_output/HDL_Adipose_Visceral_Omentum
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Adrenal_Gland -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.403 -a1 1.790 -prefix fastENLOC_output/HDL_Adrenal_Gland
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Artery_Aorta -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.416 -a1 2.308 -prefix fastENLOC_output/HDL_Artery_Aorta
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Artery_Coronary -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Artery_Coronary
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Artery_Tibial -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.443 -a1 2.946 -prefix fastENLOC_output/HDL_Artery_Tibial
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Amygdala -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 -0.000 -prefix fastENLOC_output/HDL_Brain_Amygdala
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Anterior_cingulate_cortex_BA24 -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 -0.000 -prefix fastENLOC_output/HDL_Brain_Anterior_cingulate_cortex_BA24
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Caudate_basal_ganglia -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Brain_Caudate_basal_ganglia
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Cerebellar_Hemisphere -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Brain_Cerebellar_Hemisphere
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Cerebellum -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 -0.000 -prefix fastENLOC_output/HDL_Brain_Cerebellum
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Cortex -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 -0.000 -prefix fastENLOC_output/HDL_Brain_Cortex
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Frontal_Cortex_BA9 -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 -0.000 -prefix fastENLOC_output/HDL_Brain_Frontal_Cortex_BA9
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Hippocampus -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 -0.000 -prefix fastENLOC_output/HDL_Brain_Hippocampus
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Hypothalamus -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 -0.000 -prefix fastENLOC_output/HDL_Brain_Hypothalamus
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Nucleus_accumbens_basal_ganglia -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 -0.000 -prefix fastENLOC_output/HDL_Brain_Nucleus_accumbens_basal_ganglia
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Putamen_basal_ganglia -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 -0.000 -prefix fastENLOC_output/HDL_Brain_Putamen_basal_ganglia
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Spinal_cord_cervical_c-1 -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 -0.000 -prefix fastENLOC_output/HDL_Brain_Spinal_cord_cervical_c-1
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Substantia_nigra -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Brain_Substantia_nigra
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Breast_Mammary_Tissue -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.475 -a1 3.712 -prefix fastENLOC_output/HDL_Breast_Mammary_Tissue
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Cells_Cultured_fibroblasts -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.456 -a1 3.184 -prefix fastENLOC_output/HDL_Cells_Cultured_fibroblasts
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Cells_EBV-transformed_lymphocytes -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Cells_EBV-transformed_lymphocytes
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Colon_Sigmoid -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.004 -prefix fastENLOC_output/HDL_Colon_Sigmoid
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Colon_Transverse -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.452 -a1 3.334 -prefix fastENLOC_output/HDL_Colon_Transverse
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Esophagus_Gastroesophageal_Junction -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Esophagus_Gastroesophageal_Junction
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Esophagus_Mucosa -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Esophagus_Mucosa
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Esophagus_Muscularis -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.419 -a1 2.348 -prefix fastENLOC_output/HDL_Esophagus_Muscularis
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Heart_Atrial_Appendage -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Heart_Atrial_Appendage
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Heart_Left_Ventricle -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Heart_Left_Ventricle
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Kidney_Cortex -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 -0.000 -prefix fastENLOC_output/HDL_Kidney_Cortex
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Liver -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.431 -a1 3.450 -prefix fastENLOC_output/HDL_Liver
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Lung -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.439 -a1 2.919 -prefix fastENLOC_output/HDL_Lung
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Minor_Salivary_Gland -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Minor_Salivary_Gland
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Muscle_Skeletal -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.462 -a1 3.454 -prefix fastENLOC_output/HDL_Muscle_Skeletal
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Nerve_Tibial -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.452 -a1 2.952 -prefix fastENLOC_output/HDL_Nerve_Tibial
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Ovary -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Ovary
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Pancreas -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Pancreas
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Pituitary -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Pituitary
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Prostate -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Prostate
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Skin_Not_Sun_Exposed -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.409 -a1 1.747 -prefix fastENLOC_output/HDL_Skin_Not_Sun_Exposed
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Skin_Sun_Exposed -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.471 -a1 3.311 -prefix fastENLOC_output/HDL_Skin_Sun_Exposed
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Small_Intestine_Terminal_Ileum -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Small_Intestine_Terminal_Ileum
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Spleen -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Spleen
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Stomach -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.405 -a1 1.914 -prefix fastENLOC_output/HDL_Stomach
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Testis -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.397 -a1 0.000 -prefix fastENLOC_output/HDL_Testis
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Thyroid -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Thyroid
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Uterus -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 0.000 -prefix fastENLOC_output/HDL_Uterus
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Vagina -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.396 -a1 -0.000 -prefix fastENLOC_output/HDL_Vagina
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Whole_Blood -g gwas_data/gwas/torus/HDL.torus.pip.gz -a0 -10.489 -a1 3.768 -prefix fastENLOC_output/HDL_Whole_Blood
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Adipose_Subcutaneous -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.873 -a1 3.578 -prefix fastENLOC_output/Heights_Adipose_Subcutaneous
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Adipose_Visceral_Omentum -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.846 -a1 3.386 -prefix fastENLOC_output/Heights_Adipose_Visceral_Omentum
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Adrenal_Gland -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.847 -a1 3.777 -prefix fastENLOC_output/Heights_Adrenal_Gland
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Artery_Aorta -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.892 -a1 3.921 -prefix fastENLOC_output/Heights_Artery_Aorta
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Artery_Coronary -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.841 -a1 3.826 -prefix fastENLOC_output/Heights_Artery_Coronary
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Artery_Tibial -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.891 -a1 3.770 -prefix fastENLOC_output/Heights_Artery_Tibial
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Amygdala -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.810 -a1 3.457 -prefix fastENLOC_output/Heights_Brain_Amygdala
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Anterior_cingulate_cortex_BA24 -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.811 -a1 3.301 -prefix fastENLOC_output/Heights_Brain_Anterior_cingulate_cortex_BA24
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Caudate_basal_ganglia -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.831 -a1 3.455 -prefix fastENLOC_output/Heights_Brain_Caudate_basal_ganglia
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Cerebellar_Hemisphere -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.827 -a1 3.216 -prefix fastENLOC_output/Heights_Brain_Cerebellar_Hemisphere
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Cerebellum -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.849 -a1 3.524 -prefix fastENLOC_output/Heights_Brain_Cerebellum
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Cortex -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.837 -a1 3.519 -prefix fastENLOC_output/Heights_Brain_Cortex
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Frontal_Cortex_BA9 -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.832 -a1 3.523 -prefix fastENLOC_output/Heights_Brain_Frontal_Cortex_BA9
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Hippocampus -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.816 -a1 3.337 -prefix fastENLOC_output/Heights_Brain_Hippocampus
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Hypothalamus -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.826 -a1 3.609 -prefix fastENLOC_output/Heights_Brain_Hypothalamus
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Nucleus_accumbens_basal_ganglia -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.828 -a1 3.427 -prefix fastENLOC_output/Heights_Brain_Nucleus_accumbens_basal_ganglia
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Putamen_basal_ganglia -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.839 -a1 3.716 -prefix fastENLOC_output/Heights_Brain_Putamen_basal_ganglia
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Spinal_cord_cervical_c-1 -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.809 -a1 3.293 -prefix fastENLOC_output/Heights_Brain_Spinal_cord_cervical_c-1
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Substantia_nigra -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.810 -a1 3.479 -prefix fastENLOC_output/Heights_Brain_Substantia_nigra
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Breast_Mammary_Tissue -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.860 -a1 3.682 -prefix fastENLOC_output/Heights_Breast_Mammary_Tissue
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Cells_Cultured_fibroblasts -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.891 -a1 3.767 -prefix fastENLOC_output/Heights_Cells_Cultured_fibroblasts
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Cells_EBV-transformed_lymphocytes -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.814 -a1 3.420 -prefix fastENLOC_output/Heights_Cells_EBV-transformed_lymphocytes
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Colon_Sigmoid -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.853 -a1 3.663 -prefix fastENLOC_output/Heights_Colon_Sigmoid
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Colon_Transverse -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.857 -a1 3.603 -prefix fastENLOC_output/Heights_Colon_Transverse
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Esophagus_Gastroesophageal_Junction -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.862 -a1 3.758 -prefix fastENLOC_output/Heights_Esophagus_Gastroesophageal_Junction
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Esophagus_Mucosa -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.871 -a1 3.598 -prefix fastENLOC_output/Heights_Esophagus_Mucosa
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Esophagus_Muscularis -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.869 -a1 3.597 -prefix fastENLOC_output/Heights_Esophagus_Muscularis
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Heart_Atrial_Appendage -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.858 -a1 3.660 -prefix fastENLOC_output/Heights_Heart_Atrial_Appendage
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Heart_Left_Ventricle -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.847 -a1 3.636 -prefix fastENLOC_output/Heights_Heart_Left_Ventricle
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Kidney_Cortex -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.810 -a1 3.586 -prefix fastENLOC_output/Heights_Kidney_Cortex
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Liver -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.826 -a1 3.634 -prefix fastENLOC_output/Heights_Liver
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Lung -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.874 -a1 3.654 -prefix fastENLOC_output/Heights_Lung
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Minor_Salivary_Gland -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.832 -a1 3.866 -prefix fastENLOC_output/Heights_Minor_Salivary_Gland
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Muscle_Skeletal -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.851 -a1 3.463 -prefix fastENLOC_output/Heights_Muscle_Skeletal
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Nerve_Tibial -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.877 -a1 3.451 -prefix fastENLOC_output/Heights_Nerve_Tibial
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Ovary -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.830 -a1 3.622 -prefix fastENLOC_output/Heights_Ovary
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Pancreas -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.841 -a1 3.489 -prefix fastENLOC_output/Heights_Pancreas
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Pituitary -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.850 -a1 3.704 -prefix fastENLOC_output/Heights_Pituitary
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Prostate -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.842 -a1 3.745 -prefix fastENLOC_output/Heights_Prostate
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Skin_Not_Sun_Exposed -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.875 -a1 3.604 -prefix fastENLOC_output/Heights_Skin_Not_Sun_Exposed
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Skin_Sun_Exposed -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.869 -a1 3.442 -prefix fastENLOC_output/Heights_Skin_Sun_Exposed
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Small_Intestine_Terminal_Ileum -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.832 -a1 3.609 -prefix fastENLOC_output/Heights_Small_Intestine_Terminal_Ileum
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Spleen -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.835 -a1 3.344 -prefix fastENLOC_output/Heights_Spleen
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Stomach -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.841 -a1 3.597 -prefix fastENLOC_output/Heights_Stomach
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Testis -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.878 -a1 3.415 -prefix fastENLOC_output/Heights_Testis
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Thyroid -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.876 -a1 3.413 -prefix fastENLOC_output/Heights_Thyroid
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Uterus -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.828 -a1 3.930 -prefix fastENLOC_output/Heights_Uterus
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Vagina -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.809 -a1 3.440 -prefix fastENLOC_output/Heights_Vagina
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Whole_Blood -g gwas_data/gwas/torus/Heights.torus.pip.gz -a0 -8.846 -a1 3.362 -prefix fastENLOC_output/Heights_Whole_Blood
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Adipose_Subcutaneous -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Adipose_Subcutaneous
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Adipose_Visceral_Omentum -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 -0.000 -prefix fastENLOC_output/LDL_Adipose_Visceral_Omentum
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Adrenal_Gland -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Adrenal_Gland
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Artery_Aorta -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Artery_Aorta
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Artery_Coronary -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Artery_Coronary
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Artery_Tibial -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.569 -a1 1.507 -prefix fastENLOC_output/LDL_Artery_Tibial
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Amygdala -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Brain_Amygdala
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Anterior_cingulate_cortex_BA24 -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Brain_Anterior_cingulate_cortex_BA24
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Caudate_basal_ganglia -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Brain_Caudate_basal_ganglia
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Cerebellar_Hemisphere -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Brain_Cerebellar_Hemisphere
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Cerebellum -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Brain_Cerebellum
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Cortex -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Brain_Cortex
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Frontal_Cortex_BA9 -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 -0.000 -prefix fastENLOC_output/LDL_Brain_Frontal_Cortex_BA9
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Hippocampus -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 -0.000 -prefix fastENLOC_output/LDL_Brain_Hippocampus
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Hypothalamus -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Brain_Hypothalamus
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Nucleus_accumbens_basal_ganglia -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.577 -a1 2.509 -prefix fastENLOC_output/LDL_Brain_Nucleus_accumbens_basal_ganglia
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Putamen_basal_ganglia -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Brain_Putamen_basal_ganglia
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Spinal_cord_cervical_c-1 -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 -0.000 -prefix fastENLOC_output/LDL_Brain_Spinal_cord_cervical_c-1
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Brain_Substantia_nigra -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 -0.000 -prefix fastENLOC_output/LDL_Brain_Substantia_nigra
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Breast_Mammary_Tissue -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 -0.000 -prefix fastENLOC_output/LDL_Breast_Mammary_Tissue
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Cells_Cultured_fibroblasts -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.585 -a1 2.344 -prefix fastENLOC_output/LDL_Cells_Cultured_fibroblasts
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Cells_EBV-transformed_lymphocytes -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 -0.000 -prefix fastENLOC_output/LDL_Cells_EBV-transformed_lymphocytes
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Colon_Sigmoid -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Colon_Sigmoid
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Colon_Transverse -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.578 -a1 2.270 -prefix fastENLOC_output/LDL_Colon_Transverse
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Esophagus_Gastroesophageal_Junction -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.567 -a1 1.584 -prefix fastENLOC_output/LDL_Esophagus_Gastroesophageal_Junction
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Esophagus_Mucosa -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.597 -a1 2.766 -prefix fastENLOC_output/LDL_Esophagus_Mucosa
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Esophagus_Muscularis -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 -0.000 -prefix fastENLOC_output/LDL_Esophagus_Muscularis
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Heart_Atrial_Appendage -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Heart_Atrial_Appendage
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Heart_Left_Ventricle -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Heart_Left_Ventricle
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Kidney_Cortex -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 -0.000 -prefix fastENLOC_output/LDL_Kidney_Cortex
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Liver -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.698 -a1 4.841 -prefix fastENLOC_output/LDL_Liver
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Lung -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.567 -a1 1.283 -prefix fastENLOC_output/LDL_Lung
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Minor_Salivary_Gland -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.591 -a1 3.423 -prefix fastENLOC_output/LDL_Minor_Salivary_Gland
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Muscle_Skeletal -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.001 -prefix fastENLOC_output/LDL_Muscle_Skeletal
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Nerve_Tibial -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.627 -a1 3.119 -prefix fastENLOC_output/LDL_Nerve_Tibial
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Ovary -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 -0.000 -prefix fastENLOC_output/LDL_Ovary
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Pancreas -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Pancreas
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Pituitary -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Pituitary
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Prostate -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 -0.000 -prefix fastENLOC_output/LDL_Prostate
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Skin_Not_Sun_Exposed -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Skin_Not_Sun_Exposed
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Skin_Sun_Exposed -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.581 -a1 2.070 -prefix fastENLOC_output/LDL_Skin_Sun_Exposed
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Small_Intestine_Terminal_Ileum -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Small_Intestine_Terminal_Ileum
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Spleen -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Spleen
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Stomach -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.584 -a1 2.733 -prefix fastENLOC_output/LDL_Stomach
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Testis -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.561 -a1 -0.000 -prefix fastENLOC_output/LDL_Testis
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Thyroid -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Thyroid
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Uterus -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 -0.000 -prefix fastENLOC_output/LDL_Uterus
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Vagina -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.560 -a1 0.000 -prefix fastENLOC_output/LDL_Vagina
fastenloc -e gtex_annotation/gtex_v8.eqtl_annot_coord.vcf.gz -t Whole_Blood -g gwas_data/gwas/torus/LDL.torus.pip.gz -a0 -10.605 -a1 3.023 -prefix fastENLOC_output/LDL_Whole_Blood
