perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Adipose_Subcutaneous.enloc.sig.out > fastENLOC_output/gene_level/CAD_Adipose_Subcutaneous.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Adipose_Visceral_Omentum.enloc.sig.out > fastENLOC_output/gene_level/CAD_Adipose_Visceral_Omentum.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Adrenal_Gland.enloc.sig.out > fastENLOC_output/gene_level/CAD_Adrenal_Gland.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Artery_Aorta.enloc.sig.out > fastENLOC_output/gene_level/CAD_Artery_Aorta.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Artery_Coronary.enloc.sig.out > fastENLOC_output/gene_level/CAD_Artery_Coronary.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Artery_Tibial.enloc.sig.out > fastENLOC_output/gene_level/CAD_Artery_Tibial.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Amygdala.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Amygdala.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Anterior_cingulate_cortex_BA24.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Anterior_cingulate_cortex_BA24.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Caudate_basal_ganglia.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Caudate_basal_ganglia.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Cerebellar_Hemisphere.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Cerebellar_Hemisphere.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Cerebellum.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Cerebellum.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Cortex.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Cortex.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Frontal_Cortex_BA9.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Frontal_Cortex_BA9.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Hippocampus.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Hippocampus.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Hypothalamus.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Hypothalamus.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Nucleus_accumbens_basal_ganglia.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Nucleus_accumbens_basal_ganglia.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Putamen_basal_ganglia.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Putamen_basal_ganglia.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Spinal_cord_cervical_c-1.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Spinal_cord_cervical_c-1.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Brain_Substantia_nigra.enloc.sig.out > fastENLOC_output/gene_level/CAD_Brain_Substantia_nigra.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Breast_Mammary_Tissue.enloc.sig.out > fastENLOC_output/gene_level/CAD_Breast_Mammary_Tissue.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Cells_Cultured_fibroblasts.enloc.sig.out > fastENLOC_output/gene_level/CAD_Cells_Cultured_fibroblasts.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Cells_EBV-transformed_lymphocytes.enloc.sig.out > fastENLOC_output/gene_level/CAD_Cells_EBV-transformed_lymphocytes.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Colon_Sigmoid.enloc.sig.out > fastENLOC_output/gene_level/CAD_Colon_Sigmoid.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Colon_Transverse.enloc.sig.out > fastENLOC_output/gene_level/CAD_Colon_Transverse.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Esophagus_Gastroesophageal_Junction.enloc.sig.out > fastENLOC_output/gene_level/CAD_Esophagus_Gastroesophageal_Junction.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Esophagus_Mucosa.enloc.sig.out > fastENLOC_output/gene_level/CAD_Esophagus_Mucosa.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Esophagus_Muscularis.enloc.sig.out > fastENLOC_output/gene_level/CAD_Esophagus_Muscularis.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Heart_Atrial_Appendage.enloc.sig.out > fastENLOC_output/gene_level/CAD_Heart_Atrial_Appendage.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Heart_Left_Ventricle.enloc.sig.out > fastENLOC_output/gene_level/CAD_Heart_Left_Ventricle.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Kidney_Cortex.enloc.sig.out > fastENLOC_output/gene_level/CAD_Kidney_Cortex.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Liver.enloc.sig.out > fastENLOC_output/gene_level/CAD_Liver.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Lung.enloc.sig.out > fastENLOC_output/gene_level/CAD_Lung.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Minor_Salivary_Gland.enloc.sig.out > fastENLOC_output/gene_level/CAD_Minor_Salivary_Gland.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Muscle_Skeletal.enloc.sig.out > fastENLOC_output/gene_level/CAD_Muscle_Skeletal.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Nerve_Tibial.enloc.sig.out > fastENLOC_output/gene_level/CAD_Nerve_Tibial.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Ovary.enloc.sig.out > fastENLOC_output/gene_level/CAD_Ovary.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Pancreas.enloc.sig.out > fastENLOC_output/gene_level/CAD_Pancreas.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Pituitary.enloc.sig.out > fastENLOC_output/gene_level/CAD_Pituitary.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Prostate.enloc.sig.out > fastENLOC_output/gene_level/CAD_Prostate.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Skin_Not_Sun_Exposed.enloc.sig.out > fastENLOC_output/gene_level/CAD_Skin_Not_Sun_Exposed.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Skin_Sun_Exposed.enloc.sig.out > fastENLOC_output/gene_level/CAD_Skin_Sun_Exposed.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Small_Intestine_Terminal_Ileum.enloc.sig.out > fastENLOC_output/gene_level/CAD_Small_Intestine_Terminal_Ileum.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Spleen.enloc.sig.out > fastENLOC_output/gene_level/CAD_Spleen.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Stomach.enloc.sig.out > fastENLOC_output/gene_level/CAD_Stomach.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Testis.enloc.sig.out > fastENLOC_output/gene_level/CAD_Testis.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Thyroid.enloc.sig.out > fastENLOC_output/gene_level/CAD_Thyroid.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Uterus.enloc.sig.out > fastENLOC_output/gene_level/CAD_Uterus.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Vagina.enloc.sig.out > fastENLOC_output/gene_level/CAD_Vagina.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/CAD_Whole_Blood.enloc.sig.out > fastENLOC_output/gene_level/CAD_Whole_Blood.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Adipose_Subcutaneous.enloc.sig.out > fastENLOC_output/gene_level/HDL_Adipose_Subcutaneous.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Adipose_Visceral_Omentum.enloc.sig.out > fastENLOC_output/gene_level/HDL_Adipose_Visceral_Omentum.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Adrenal_Gland.enloc.sig.out > fastENLOC_output/gene_level/HDL_Adrenal_Gland.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Artery_Aorta.enloc.sig.out > fastENLOC_output/gene_level/HDL_Artery_Aorta.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Artery_Coronary.enloc.sig.out > fastENLOC_output/gene_level/HDL_Artery_Coronary.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Artery_Tibial.enloc.sig.out > fastENLOC_output/gene_level/HDL_Artery_Tibial.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Amygdala.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Amygdala.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Anterior_cingulate_cortex_BA24.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Anterior_cingulate_cortex_BA24.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Caudate_basal_ganglia.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Caudate_basal_ganglia.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Cerebellar_Hemisphere.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Cerebellar_Hemisphere.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Cerebellum.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Cerebellum.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Cortex.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Cortex.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Frontal_Cortex_BA9.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Frontal_Cortex_BA9.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Hippocampus.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Hippocampus.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Hypothalamus.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Hypothalamus.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Nucleus_accumbens_basal_ganglia.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Nucleus_accumbens_basal_ganglia.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Putamen_basal_ganglia.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Putamen_basal_ganglia.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Spinal_cord_cervical_c-1.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Spinal_cord_cervical_c-1.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Brain_Substantia_nigra.enloc.sig.out > fastENLOC_output/gene_level/HDL_Brain_Substantia_nigra.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Breast_Mammary_Tissue.enloc.sig.out > fastENLOC_output/gene_level/HDL_Breast_Mammary_Tissue.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Cells_Cultured_fibroblasts.enloc.sig.out > fastENLOC_output/gene_level/HDL_Cells_Cultured_fibroblasts.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Cells_EBV-transformed_lymphocytes.enloc.sig.out > fastENLOC_output/gene_level/HDL_Cells_EBV-transformed_lymphocytes.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Colon_Sigmoid.enloc.sig.out > fastENLOC_output/gene_level/HDL_Colon_Sigmoid.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Colon_Transverse.enloc.sig.out > fastENLOC_output/gene_level/HDL_Colon_Transverse.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Esophagus_Gastroesophageal_Junction.enloc.sig.out > fastENLOC_output/gene_level/HDL_Esophagus_Gastroesophageal_Junction.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Esophagus_Mucosa.enloc.sig.out > fastENLOC_output/gene_level/HDL_Esophagus_Mucosa.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Esophagus_Muscularis.enloc.sig.out > fastENLOC_output/gene_level/HDL_Esophagus_Muscularis.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Heart_Atrial_Appendage.enloc.sig.out > fastENLOC_output/gene_level/HDL_Heart_Atrial_Appendage.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Heart_Left_Ventricle.enloc.sig.out > fastENLOC_output/gene_level/HDL_Heart_Left_Ventricle.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Kidney_Cortex.enloc.sig.out > fastENLOC_output/gene_level/HDL_Kidney_Cortex.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Liver.enloc.sig.out > fastENLOC_output/gene_level/HDL_Liver.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Lung.enloc.sig.out > fastENLOC_output/gene_level/HDL_Lung.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Minor_Salivary_Gland.enloc.sig.out > fastENLOC_output/gene_level/HDL_Minor_Salivary_Gland.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Muscle_Skeletal.enloc.sig.out > fastENLOC_output/gene_level/HDL_Muscle_Skeletal.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Nerve_Tibial.enloc.sig.out > fastENLOC_output/gene_level/HDL_Nerve_Tibial.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Ovary.enloc.sig.out > fastENLOC_output/gene_level/HDL_Ovary.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Pancreas.enloc.sig.out > fastENLOC_output/gene_level/HDL_Pancreas.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Pituitary.enloc.sig.out > fastENLOC_output/gene_level/HDL_Pituitary.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Prostate.enloc.sig.out > fastENLOC_output/gene_level/HDL_Prostate.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Skin_Not_Sun_Exposed.enloc.sig.out > fastENLOC_output/gene_level/HDL_Skin_Not_Sun_Exposed.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Skin_Sun_Exposed.enloc.sig.out > fastENLOC_output/gene_level/HDL_Skin_Sun_Exposed.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Small_Intestine_Terminal_Ileum.enloc.sig.out > fastENLOC_output/gene_level/HDL_Small_Intestine_Terminal_Ileum.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Spleen.enloc.sig.out > fastENLOC_output/gene_level/HDL_Spleen.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Stomach.enloc.sig.out > fastENLOC_output/gene_level/HDL_Stomach.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Testis.enloc.sig.out > fastENLOC_output/gene_level/HDL_Testis.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Thyroid.enloc.sig.out > fastENLOC_output/gene_level/HDL_Thyroid.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Uterus.enloc.sig.out > fastENLOC_output/gene_level/HDL_Uterus.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Vagina.enloc.sig.out > fastENLOC_output/gene_level/HDL_Vagina.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/HDL_Whole_Blood.enloc.sig.out > fastENLOC_output/gene_level/HDL_Whole_Blood.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Adipose_Subcutaneous.enloc.sig.out > fastENLOC_output/gene_level/Heights_Adipose_Subcutaneous.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Adipose_Visceral_Omentum.enloc.sig.out > fastENLOC_output/gene_level/Heights_Adipose_Visceral_Omentum.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Adrenal_Gland.enloc.sig.out > fastENLOC_output/gene_level/Heights_Adrenal_Gland.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Artery_Aorta.enloc.sig.out > fastENLOC_output/gene_level/Heights_Artery_Aorta.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Artery_Coronary.enloc.sig.out > fastENLOC_output/gene_level/Heights_Artery_Coronary.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Artery_Tibial.enloc.sig.out > fastENLOC_output/gene_level/Heights_Artery_Tibial.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Amygdala.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Amygdala.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Anterior_cingulate_cortex_BA24.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Anterior_cingulate_cortex_BA24.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Caudate_basal_ganglia.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Caudate_basal_ganglia.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Cerebellar_Hemisphere.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Cerebellar_Hemisphere.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Cerebellum.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Cerebellum.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Cortex.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Cortex.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Frontal_Cortex_BA9.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Frontal_Cortex_BA9.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Hippocampus.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Hippocampus.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Hypothalamus.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Hypothalamus.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Nucleus_accumbens_basal_ganglia.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Nucleus_accumbens_basal_ganglia.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Putamen_basal_ganglia.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Putamen_basal_ganglia.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Spinal_cord_cervical_c-1.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Spinal_cord_cervical_c-1.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Brain_Substantia_nigra.enloc.sig.out > fastENLOC_output/gene_level/Heights_Brain_Substantia_nigra.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Breast_Mammary_Tissue.enloc.sig.out > fastENLOC_output/gene_level/Heights_Breast_Mammary_Tissue.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Cells_Cultured_fibroblasts.enloc.sig.out > fastENLOC_output/gene_level/Heights_Cells_Cultured_fibroblasts.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Cells_EBV-transformed_lymphocytes.enloc.sig.out > fastENLOC_output/gene_level/Heights_Cells_EBV-transformed_lymphocytes.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Colon_Sigmoid.enloc.sig.out > fastENLOC_output/gene_level/Heights_Colon_Sigmoid.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Colon_Transverse.enloc.sig.out > fastENLOC_output/gene_level/Heights_Colon_Transverse.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Esophagus_Gastroesophageal_Junction.enloc.sig.out > fastENLOC_output/gene_level/Heights_Esophagus_Gastroesophageal_Junction.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Esophagus_Mucosa.enloc.sig.out > fastENLOC_output/gene_level/Heights_Esophagus_Mucosa.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Esophagus_Muscularis.enloc.sig.out > fastENLOC_output/gene_level/Heights_Esophagus_Muscularis.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Heart_Atrial_Appendage.enloc.sig.out > fastENLOC_output/gene_level/Heights_Heart_Atrial_Appendage.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Heart_Left_Ventricle.enloc.sig.out > fastENLOC_output/gene_level/Heights_Heart_Left_Ventricle.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Kidney_Cortex.enloc.sig.out > fastENLOC_output/gene_level/Heights_Kidney_Cortex.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Liver.enloc.sig.out > fastENLOC_output/gene_level/Heights_Liver.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Lung.enloc.sig.out > fastENLOC_output/gene_level/Heights_Lung.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Minor_Salivary_Gland.enloc.sig.out > fastENLOC_output/gene_level/Heights_Minor_Salivary_Gland.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Muscle_Skeletal.enloc.sig.out > fastENLOC_output/gene_level/Heights_Muscle_Skeletal.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Nerve_Tibial.enloc.sig.out > fastENLOC_output/gene_level/Heights_Nerve_Tibial.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Ovary.enloc.sig.out > fastENLOC_output/gene_level/Heights_Ovary.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Pancreas.enloc.sig.out > fastENLOC_output/gene_level/Heights_Pancreas.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Pituitary.enloc.sig.out > fastENLOC_output/gene_level/Heights_Pituitary.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Prostate.enloc.sig.out > fastENLOC_output/gene_level/Heights_Prostate.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Skin_Not_Sun_Exposed.enloc.sig.out > fastENLOC_output/gene_level/Heights_Skin_Not_Sun_Exposed.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Skin_Sun_Exposed.enloc.sig.out > fastENLOC_output/gene_level/Heights_Skin_Sun_Exposed.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Small_Intestine_Terminal_Ileum.enloc.sig.out > fastENLOC_output/gene_level/Heights_Small_Intestine_Terminal_Ileum.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Spleen.enloc.sig.out > fastENLOC_output/gene_level/Heights_Spleen.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Stomach.enloc.sig.out > fastENLOC_output/gene_level/Heights_Stomach.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Testis.enloc.sig.out > fastENLOC_output/gene_level/Heights_Testis.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Thyroid.enloc.sig.out > fastENLOC_output/gene_level/Heights_Thyroid.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Uterus.enloc.sig.out > fastENLOC_output/gene_level/Heights_Uterus.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Vagina.enloc.sig.out > fastENLOC_output/gene_level/Heights_Vagina.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/Heights_Whole_Blood.enloc.sig.out > fastENLOC_output/gene_level/Heights_Whole_Blood.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Adipose_Subcutaneous.enloc.sig.out > fastENLOC_output/gene_level/LDL_Adipose_Subcutaneous.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Adipose_Visceral_Omentum.enloc.sig.out > fastENLOC_output/gene_level/LDL_Adipose_Visceral_Omentum.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Adrenal_Gland.enloc.sig.out > fastENLOC_output/gene_level/LDL_Adrenal_Gland.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Artery_Aorta.enloc.sig.out > fastENLOC_output/gene_level/LDL_Artery_Aorta.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Artery_Coronary.enloc.sig.out > fastENLOC_output/gene_level/LDL_Artery_Coronary.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Artery_Tibial.enloc.sig.out > fastENLOC_output/gene_level/LDL_Artery_Tibial.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Amygdala.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Amygdala.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Anterior_cingulate_cortex_BA24.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Anterior_cingulate_cortex_BA24.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Caudate_basal_ganglia.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Caudate_basal_ganglia.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Cerebellar_Hemisphere.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Cerebellar_Hemisphere.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Cerebellum.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Cerebellum.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Cortex.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Cortex.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Frontal_Cortex_BA9.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Frontal_Cortex_BA9.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Hippocampus.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Hippocampus.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Hypothalamus.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Hypothalamus.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Nucleus_accumbens_basal_ganglia.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Nucleus_accumbens_basal_ganglia.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Putamen_basal_ganglia.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Putamen_basal_ganglia.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Spinal_cord_cervical_c-1.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Spinal_cord_cervical_c-1.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Brain_Substantia_nigra.enloc.sig.out > fastENLOC_output/gene_level/LDL_Brain_Substantia_nigra.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Breast_Mammary_Tissue.enloc.sig.out > fastENLOC_output/gene_level/LDL_Breast_Mammary_Tissue.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Cells_Cultured_fibroblasts.enloc.sig.out > fastENLOC_output/gene_level/LDL_Cells_Cultured_fibroblasts.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Cells_EBV-transformed_lymphocytes.enloc.sig.out > fastENLOC_output/gene_level/LDL_Cells_EBV-transformed_lymphocytes.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Colon_Sigmoid.enloc.sig.out > fastENLOC_output/gene_level/LDL_Colon_Sigmoid.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Colon_Transverse.enloc.sig.out > fastENLOC_output/gene_level/LDL_Colon_Transverse.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Esophagus_Gastroesophageal_Junction.enloc.sig.out > fastENLOC_output/gene_level/LDL_Esophagus_Gastroesophageal_Junction.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Esophagus_Mucosa.enloc.sig.out > fastENLOC_output/gene_level/LDL_Esophagus_Mucosa.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Esophagus_Muscularis.enloc.sig.out > fastENLOC_output/gene_level/LDL_Esophagus_Muscularis.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Heart_Atrial_Appendage.enloc.sig.out > fastENLOC_output/gene_level/LDL_Heart_Atrial_Appendage.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Heart_Left_Ventricle.enloc.sig.out > fastENLOC_output/gene_level/LDL_Heart_Left_Ventricle.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Kidney_Cortex.enloc.sig.out > fastENLOC_output/gene_level/LDL_Kidney_Cortex.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Liver.enloc.sig.out > fastENLOC_output/gene_level/LDL_Liver.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Lung.enloc.sig.out > fastENLOC_output/gene_level/LDL_Lung.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Minor_Salivary_Gland.enloc.sig.out > fastENLOC_output/gene_level/LDL_Minor_Salivary_Gland.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Muscle_Skeletal.enloc.sig.out > fastENLOC_output/gene_level/LDL_Muscle_Skeletal.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Nerve_Tibial.enloc.sig.out > fastENLOC_output/gene_level/LDL_Nerve_Tibial.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Ovary.enloc.sig.out > fastENLOC_output/gene_level/LDL_Ovary.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Pancreas.enloc.sig.out > fastENLOC_output/gene_level/LDL_Pancreas.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Pituitary.enloc.sig.out > fastENLOC_output/gene_level/LDL_Pituitary.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Prostate.enloc.sig.out > fastENLOC_output/gene_level/LDL_Prostate.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Skin_Not_Sun_Exposed.enloc.sig.out > fastENLOC_output/gene_level/LDL_Skin_Not_Sun_Exposed.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Skin_Sun_Exposed.enloc.sig.out > fastENLOC_output/gene_level/LDL_Skin_Sun_Exposed.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Small_Intestine_Terminal_Ileum.enloc.sig.out > fastENLOC_output/gene_level/LDL_Small_Intestine_Terminal_Ileum.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Spleen.enloc.sig.out > fastENLOC_output/gene_level/LDL_Spleen.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Stomach.enloc.sig.out > fastENLOC_output/gene_level/LDL_Stomach.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Testis.enloc.sig.out > fastENLOC_output/gene_level/LDL_Testis.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Thyroid.enloc.sig.out > fastENLOC_output/gene_level/LDL_Thyroid.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Uterus.enloc.sig.out > fastENLOC_output/gene_level/LDL_Uterus.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Vagina.enloc.sig.out > fastENLOC_output/gene_level/LDL_Vagina.enloc.gene.out
perl scripts/process_enloc_gene.pl fastENLOC_output/LDL_Whole_Blood.enloc.sig.out > fastENLOC_output/gene_level/LDL_Whole_Blood.enloc.gene.out
